name: bbo_acm_dlcdetect-orig
channels:
  - defaults
dependencies:
  - numpy
  - python=3.7
  - matplotlib
  - pip
  - ffmpeg
  - tensorflow<2.0
  - wxpython
  - opencv
  - pandas
  - tqdm 
  - pyyaml
  - ruamel
  - ruamel.yaml
  - scikit-image
  - scikit-learn
  - statsmodels
  - pip:
    - argparse
    - scikit-image
    - easydict
