name: bbo_acm_dlcdetect-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - python=3.7
  - matplotlib
  - pip
  - ffmpeg
  - cudnn=7
  - jupyter
  - nb_conda
  - Shapely
  - pip:
    - bbo-ccvtools
    - tensorflow-gpu==1.15.5
    - argparse
    - deeplabcut<2.2 #DLC used originally: 2.1.6.4. For 2.1.1, this installs the headless version and --headless switch is not needed anymore
