name: bbo_acm_dlcdetect-orig
channels:
  - defaults
dependencies:
  - python=3.7
  - matplotlib
  - pip
  - ffmpeg
  - cudnn=7
  - wxpython
  - opencv
  - pandas
  - tqdm 
  - pyyaml
  - ruamel
  - ruamel.yaml
  - pip:
    - statsmodels
    - scikit-image<0.19
    - scikit-learn
    - numpy
    - tensorflow-gpu==1.15.5
    - argparse
    - easydict
