name: bbo_acm_dlcdetect
channels:
  - defaults
dependencies:
  - numpy
  - python=3.7
  - matplotlib
  - pip
  - ffmpeg
  - tensorflow<2.0
  - scikit-image<0.19
  - wxpython
  - opencv
  - pandas
  - tqdm
  - pyyaml
  - ruamel
  - ruamel.yaml
  - pip:
    - easydict
    - argparse
    - deeplabcut==2.1.6.4 #DLC used originally: 2.1.6.4 - other version seem problematic
